[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["miralabs-tech"]
license = "MIT"
repository = "https://github.com/miralabs-tech/standarx-dsl"
rust-version = "1.95"

[workspace.dependencies]
standarx-dsl = { version = "0.1.0", path = "crates/standarx-dsl" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
proptest = "1"
