/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LBRACK = 4,
  anon_sym_COMMA = 5,
  anon_sym_RBRACK = 6,
  anon_sym_DOT = 7,
  anon_sym_DQUOTE = 8,
  aux_sym_plain_string_token1 = 9,
  anon_sym_BQUOTE = 10,
  aux_sym_template_inline_token1 = 11,
  anon_sym_DOLLAR = 12,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 13,
  aux_sym_template_multiline_token1 = 14,
  aux_sym_template_multiline_token2 = 15,
  aux_sym_template_multiline_token3 = 16,
  anon_sym_DOLLAR_LBRACE = 17,
  sym_escape_sequence = 18,
  sym_integer = 19,
  sym_float = 20,
  anon_sym_true = 21,
  anon_sym_false = 22,
  sym_null = 23,
  sym_comment = 24,
  sym_source_file = 25,
  sym__stmt = 26,
  sym_block = 27,
  sym_assignment = 28,
  sym__stmt_value = 29,
  sym__value = 30,
  sym_list = 31,
  sym_map = 32,
  sym_ref = 33,
  sym_plain_string = 34,
  sym_template_inline = 35,
  sym_template_multiline = 36,
  sym_interpolation = 37,
  sym__interp_expr = 38,
  sym_boolean = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_list_repeat1 = 41,
  aux_sym_map_repeat1 = 42,
  aux_sym_ref_repeat1 = 43,
  aux_sym_plain_string_repeat1 = 44,
  aux_sym_template_inline_repeat1 = 45,
  aux_sym_template_multiline_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DOT] = ".",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_plain_string_token1] = "plain_string_token1",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_template_inline_token1] = "template_inline_token1",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [aux_sym_template_multiline_token1] = "template_multiline_token1",
  [aux_sym_template_multiline_token2] = "template_multiline_token2",
  [aux_sym_template_multiline_token3] = "template_multiline_token3",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [sym_escape_sequence] = "escape_sequence",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__stmt] = "_stmt",
  [sym_block] = "block",
  [sym_assignment] = "assignment",
  [sym__stmt_value] = "_stmt_value",
  [sym__value] = "_value",
  [sym_list] = "list",
  [sym_map] = "map",
  [sym_ref] = "ref",
  [sym_plain_string] = "plain_string",
  [sym_template_inline] = "template_inline",
  [sym_template_multiline] = "template_multiline",
  [sym_interpolation] = "interpolation",
  [sym__interp_expr] = "_interp_expr",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_ref_repeat1] = "ref_repeat1",
  [aux_sym_plain_string_repeat1] = "plain_string_repeat1",
  [aux_sym_template_inline_repeat1] = "template_inline_repeat1",
  [aux_sym_template_multiline_repeat1] = "template_multiline_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_plain_string_token1] = aux_sym_plain_string_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_template_inline_token1] = aux_sym_template_inline_token1,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [aux_sym_template_multiline_token1] = aux_sym_template_multiline_token1,
  [aux_sym_template_multiline_token2] = aux_sym_template_multiline_token2,
  [aux_sym_template_multiline_token3] = aux_sym_template_multiline_token3,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__stmt] = sym__stmt,
  [sym_block] = sym_block,
  [sym_assignment] = sym_assignment,
  [sym__stmt_value] = sym__stmt_value,
  [sym__value] = sym__value,
  [sym_list] = sym_list,
  [sym_map] = sym_map,
  [sym_ref] = sym_ref,
  [sym_plain_string] = sym_plain_string,
  [sym_template_inline] = sym_template_inline,
  [sym_template_multiline] = sym_template_multiline,
  [sym_interpolation] = sym_interpolation,
  [sym__interp_expr] = sym__interp_expr,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_ref_repeat1] = aux_sym_ref_repeat1,
  [aux_sym_plain_string_repeat1] = aux_sym_plain_string_repeat1,
  [aux_sym_template_inline_repeat1] = aux_sym_template_inline_repeat1,
  [aux_sym_template_multiline_repeat1] = aux_sym_template_multiline_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_plain_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_template_inline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_template_multiline_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_template_multiline_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_template_multiline_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt_value] = {
    .visible = false,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_string] = {
    .visible = true,
    .named = true,
  },
  [sym_template_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_template_multiline] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym__interp_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_ref_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_plain_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_template_inline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_template_multiline_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_kind = 2,
  field_label = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_kind] = "kind",
  [field_label] = "label",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 1},
  [2] =
    {field_kind, 0},
  [3] =
    {field_kind, 0},
    {field_label, 1},
  [5] =
    {field_key, 1, .inherited = true},
    {field_value, 1, .inherited = true},
  [7] =
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 32,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 57,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '"', 27,
        '#', 49,
        '$', 36,
        ',', 24,
        '-', 16,
        '.', 26,
        '[', 23,
        '\\', 7,
        ']', 25,
        '`', 32,
        '{', 21,
        '}', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '$') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '`') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '"') ADVANCE(27);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '\\') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(38);
      if (lookahead == '$') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '`') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '`') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(37);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '`') ADVANCE(5);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        'u', 8,
        '"', 44,
        '$', 44,
        '\'', 44,
        '0', 44,
        '\\', 44,
        '`', 44,
        'n', 44,
        'r', 44,
        't', 44,
      );
      END_STATE();
    case 8:
      if (lookahead == '{') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(44);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == '}') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == '}') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == '}') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_plain_string_token1);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '#' &&
          lookahead != '\\') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_plain_string_token1);
      if (lookahead == '"' ||
          lookahead == '\\') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_plain_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      if (lookahead == '`') ADVANCE(4);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_template_inline_token1);
      if (lookahead == '#') ADVANCE(34);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_template_inline_token1);
      if (lookahead == '$' ||
          lookahead == '\\' ||
          lookahead == '`') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_template_inline_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_template_multiline_token1);
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == '$' ||
          lookahead == '\\' ||
          lookahead == '`') ADVANCE(49);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_template_multiline_token1);
      if (lookahead == '#') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '#' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_template_multiline_token1);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_template_multiline_token2);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_template_multiline_token3);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(49);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym__stmt] = STATE(36),
    [sym_block] = STATE(36),
    [sym_assignment] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      anon_sym_RBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(25), 1,
      sym_float,
    STATE(3), 1,
      aux_sym_list_repeat1,
    ACTIONS(23), 2,
      sym_integer,
      sym_null,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym__value,
      sym_list,
      sym_map,
      sym_ref,
      sym_plain_string,
      sym_template_inline,
      sym_template_multiline,
      sym_boolean,
  [49] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(25), 1,
      sym_float,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    STATE(4), 1,
      aux_sym_list_repeat1,
    ACTIONS(23), 2,
      sym_integer,
      sym_null,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym__value,
      sym_list,
      sym_map,
      sym_ref,
      sym_plain_string,
      sym_template_inline,
      sym_template_multiline,
      sym_boolean,
  [98] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(31), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_LBRACE,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_RBRACK,
    ACTIONS(42), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_BQUOTE,
    ACTIONS(48), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(54), 1,
      sym_float,
    STATE(4), 1,
      aux_sym_list_repeat1,
    ACTIONS(51), 2,
      sym_integer,
      sym_null,
    ACTIONS(57), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 8,
      sym__value,
      sym_list,
      sym_map,
      sym_ref,
      sym_plain_string,
      sym_template_inline,
      sym_template_multiline,
      sym_boolean,
  [147] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(62), 1,
      sym_float,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(60), 2,
      sym_integer,
      sym_null,
    STATE(50), 8,
      sym__value,
      sym_list,
      sym_map,
      sym_ref,
      sym_plain_string,
      sym_template_inline,
      sym_template_multiline,
      sym_boolean,
  [190] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_BQUOTE,
    ACTIONS(21), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      sym_float,
    STATE(40), 1,
      sym_plain_string,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(66), 2,
      sym_integer,
      sym_null,
    STATE(45), 6,
      sym__stmt_value,
      sym_list,
      sym_ref,
      sym_template_inline,
      sym_template_multiline,
      sym_boolean,
  [234] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_DOT,
    STATE(7), 1,
      aux_sym_ref_repeat1,
    ACTIONS(72), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(70), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [263] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DOT,
    STATE(7), 1,
      aux_sym_ref_repeat1,
    ACTIONS(79), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(77), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [292] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(87), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(70), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DOT,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [364] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(91), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [387] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(95), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [410] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(99), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [433] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(103), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [456] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(107), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [479] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(111), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [502] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(115), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [525] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(121), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [547] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(125), 8,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [569] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_COMMA,
    ACTIONS(127), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
    ACTIONS(129), 6,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
  [592] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 6,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      sym_float,
    ACTIONS(133), 6,
      anon_sym_BQUOTE,
      sym_integer,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym_identifier,
  [612] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(139), 1,
      sym_float,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(137), 2,
      sym_integer,
      sym_null,
    STATE(57), 4,
      sym_ref,
      sym_plain_string,
      sym__interp_expr,
      sym_boolean,
  [639] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      sym_identifier,
    ACTIONS(143), 1,
      sym_float,
    ACTIONS(27), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(141), 2,
      sym_integer,
      sym_null,
    STATE(58), 4,
      sym_ref,
      sym_plain_string,
      sym__interp_expr,
      sym_boolean,
  [666] = 5,
    ACTIONS(147), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(149), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(151), 1,
      sym_comment,
    STATE(27), 2,
      sym_interpolation,
      aux_sym_template_multiline_repeat1,
    ACTIONS(145), 5,
      anon_sym_DOLLAR,
      aux_sym_template_multiline_token1,
      aux_sym_template_multiline_token2,
      aux_sym_template_multiline_token3,
      sym_escape_sequence,
  [687] = 5,
    ACTIONS(149), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    STATE(25), 2,
      sym_interpolation,
      aux_sym_template_multiline_repeat1,
    ACTIONS(153), 5,
      anon_sym_DOLLAR,
      aux_sym_template_multiline_token1,
      aux_sym_template_multiline_token2,
      aux_sym_template_multiline_token3,
      sym_escape_sequence,
  [708] = 5,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
    ACTIONS(162), 1,
      anon_sym_DOLLAR_LBRACE,
    STATE(27), 2,
      sym_interpolation,
      aux_sym_template_multiline_repeat1,
    ACTIONS(157), 5,
      anon_sym_DOLLAR,
      aux_sym_template_multiline_token1,
      aux_sym_template_multiline_token2,
      aux_sym_template_multiline_token3,
      sym_escape_sequence,
  [729] = 5,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_BQUOTE,
    ACTIONS(169), 1,
      anon_sym_DOLLAR_LBRACE,
    STATE(31), 2,
      sym_interpolation,
      aux_sym_template_inline_repeat1,
    ACTIONS(167), 3,
      aux_sym_template_inline_token1,
      anon_sym_DOLLAR,
      sym_escape_sequence,
  [748] = 5,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(171), 1,
      anon_sym_BQUOTE,
    STATE(28), 2,
      sym_interpolation,
      aux_sym_template_inline_repeat1,
    ACTIONS(173), 3,
      aux_sym_template_inline_token1,
      anon_sym_DOLLAR,
      sym_escape_sequence,
  [767] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(175), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(30), 4,
      sym__stmt,
      sym_block,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [784] = 5,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_BQUOTE,
    ACTIONS(185), 1,
      anon_sym_DOLLAR_LBRACE,
    STATE(31), 2,
      sym_interpolation,
      aux_sym_template_inline_repeat1,
    ACTIONS(182), 3,
      aux_sym_template_inline_token1,
      anon_sym_DOLLAR,
      sym_escape_sequence,
  [803] = 2,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(188), 7,
      anon_sym_DOLLAR,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
      aux_sym_template_multiline_token1,
      aux_sym_template_multiline_token2,
      aux_sym_template_multiline_token3,
      anon_sym_DOLLAR_LBRACE,
      sym_escape_sequence,
  [816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    STATE(30), 4,
      sym__stmt,
      sym_block,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [832] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    STATE(30), 4,
      sym__stmt,
      sym_block,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [848] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(34), 4,
      sym__stmt,
      sym_block,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [864] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    STATE(30), 4,
      sym__stmt,
      sym_block,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [880] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(198), 1,
      anon_sym_RBRACE,
    STATE(33), 4,
      sym__stmt,
      sym_block,
      sym_assignment,
      aux_sym_source_file_repeat1,
  [896] = 2,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(188), 5,
      anon_sym_BQUOTE,
      aux_sym_template_inline_token1,
      anon_sym_DOLLAR,
      anon_sym_DOLLAR_LBRACE,
      sym_escape_sequence,
  [907] = 4,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_plain_string_repeat1,
    ACTIONS(202), 2,
      aux_sym_plain_string_token1,
      sym_escape_sequence,
  [921] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
  [933] = 4,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(208), 1,
      anon_sym_DQUOTE,
    STATE(41), 1,
      aux_sym_plain_string_repeat1,
    ACTIONS(210), 2,
      aux_sym_plain_string_token1,
      sym_escape_sequence,
  [947] = 4,
    ACTIONS(151), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      aux_sym_plain_string_repeat1,
    ACTIONS(215), 2,
      aux_sym_plain_string_token1,
      sym_escape_sequence,
  [961] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DOT,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      aux_sym_ref_repeat1,
  [974] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      aux_sym_map_repeat1,
  [987] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(223), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
  [996] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
  [1005] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
  [1014] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
  [1023] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      sym_identifier,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      aux_sym_map_repeat1,
  [1036] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    ACTIONS(236), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 3,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_identifier,
  [1056] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_identifier,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      aux_sym_map_repeat1,
  [1069] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(244), 1,
      sym_identifier,
    STATE(11), 1,
      sym_plain_string,
  [1082] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_DOT,
    STATE(8), 1,
      aux_sym_ref_repeat1,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [1100] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
  [1107] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
  [1114] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 147,
  [SMALL_STATE(6)] = 190,
  [SMALL_STATE(7)] = 234,
  [SMALL_STATE(8)] = 263,
  [SMALL_STATE(9)] = 292,
  [SMALL_STATE(10)] = 316,
  [SMALL_STATE(11)] = 340,
  [SMALL_STATE(12)] = 364,
  [SMALL_STATE(13)] = 387,
  [SMALL_STATE(14)] = 410,
  [SMALL_STATE(15)] = 433,
  [SMALL_STATE(16)] = 456,
  [SMALL_STATE(17)] = 479,
  [SMALL_STATE(18)] = 502,
  [SMALL_STATE(19)] = 525,
  [SMALL_STATE(20)] = 547,
  [SMALL_STATE(21)] = 569,
  [SMALL_STATE(22)] = 592,
  [SMALL_STATE(23)] = 612,
  [SMALL_STATE(24)] = 639,
  [SMALL_STATE(25)] = 666,
  [SMALL_STATE(26)] = 687,
  [SMALL_STATE(27)] = 708,
  [SMALL_STATE(28)] = 729,
  [SMALL_STATE(29)] = 748,
  [SMALL_STATE(30)] = 767,
  [SMALL_STATE(31)] = 784,
  [SMALL_STATE(32)] = 803,
  [SMALL_STATE(33)] = 816,
  [SMALL_STATE(34)] = 832,
  [SMALL_STATE(35)] = 848,
  [SMALL_STATE(36)] = 864,
  [SMALL_STATE(37)] = 880,
  [SMALL_STATE(38)] = 896,
  [SMALL_STATE(39)] = 907,
  [SMALL_STATE(40)] = 921,
  [SMALL_STATE(41)] = 933,
  [SMALL_STATE(42)] = 947,
  [SMALL_STATE(43)] = 961,
  [SMALL_STATE(44)] = 974,
  [SMALL_STATE(45)] = 987,
  [SMALL_STATE(46)] = 996,
  [SMALL_STATE(47)] = 1005,
  [SMALL_STATE(48)] = 1014,
  [SMALL_STATE(49)] = 1023,
  [SMALL_STATE(50)] = 1036,
  [SMALL_STATE(51)] = 1047,
  [SMALL_STATE(52)] = 1056,
  [SMALL_STATE(53)] = 1069,
  [SMALL_STATE(54)] = 1082,
  [SMALL_STATE(55)] = 1092,
  [SMALL_STATE(56)] = 1100,
  [SMALL_STATE(57)] = 1107,
  [SMALL_STATE(58)] = 1114,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_ref_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_ref_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_ref_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ref, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ref, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_string, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_string, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_string, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plain_string, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_inline, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_inline, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_multiline, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_multiline, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_inline, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_inline, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_multiline, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_multiline, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, 0, 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, 0, 4),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_multiline_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_template_multiline_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_multiline_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_template_inline_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_inline_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stmt_value, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_plain_string_repeat1, 2, 0, 0),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_plain_string_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__interp_expr, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 2),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 5), SHIFT_REPEAT(5),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 5),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, 0, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5, 0, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 3, 0, 1),
  [248] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_standarx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
